# [START admin_protection]
runtime: php55
api_version: 1
threadsafe: yes

handlers:
# [END admin_protection]
#- url: /.*
- url: /
  script: index.php
- url: /createtask
  script: createtask.php
- url: /kronjot
  script: kronjot.php
- url: /queue
  script: queue.php
